name: Build LaTeX document

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v1
      - name: Compile Scala Sandbox
        uses: dante-ev/latex-action@master
        with:
          working_directory: src
          root_file: ScalaSandbox.tex
          args: -pdf -output-directory=../out -interaction=nonstopmode -synctex=1
      - name: Check pdf files
        run: |
          file out/ScalaSandbox.pdf | grep -q ' PDF '
      - name: Upload Scala Sandbox PDF
        uses: actions/upload-artifact@master
        with:
          name: lecture
          path: out/ScalaSandbox.pdf
      - name: Upload Scala Sandbox
        uses: actions/upload-artifact@master
        with:
          name: lecture
          path: out/ScalaSandbox.pdf